services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-microservice
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - power-track-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  power-track-network:
    external: true  # <- tornar a rede compartilhada

